AppBuilder/platform/views/ABViewDocxBuilder.js
=> Add cypress data-cy attributes to docx download buttons

AppBuilder/platform/views/ABViewDetailCheckbox.js, AppBuilder/platform/views/ABViewDetailCustom.js, AppBuilder/platform/views/ABViewDetailImage.js, AppBuilder/platform/views/ABViewDetailSelectivity.js, AppBuilder/platform/views/ABViewDetailText.js
=> [add] cypress data-cy attributes to detail fields

AppBuilder/platform/views/ABViewDataview.js, AppBuilder/platform/views/ABViewDetailCheckbox.js, AppBuilder/platform/views/ABViewDetailCustom.js, AppBuilder/platform/views/ABViewDetailImage.js, AppBuilder/platform/views/ABViewDetailSelectivity.js, AppBuilder/platform/views/ABViewDetailText.js, AppBuilder/platform/views/ABViewDocxBuilder.js
Requires changes to core: appdevdesigns/appbuilder_class_core#44
- Switch to use names not label
- Follow the format used in other attributes
=> Update data-cy attributes to use name not label and improve format

AppBuilder/platform/views/ABViewMenu.js
Previously attributes were not added to menus outside of tabs.
=> [fix] data-cy attributes added to all menu items

AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
Line 914 is the only change other than the linting.
An alternate approach would be to change lines 984 and 986 replacing `this._formData` with `objectToUpdate`.
=> Hotfix form data record rules2

index.js
=> Fix loading Webix components

AppBuilder/platform/ABApplication.js
add create/delete pages support to ABApplication.js
https://github.com/digi-serve/plugin_ABDesigner/issues/3
=> [add] support for pages

ui/portal_auth_login_resetPassword.js, ui/portal_auth_login_resetRequest.js
Fixes our failing test in `0001_portal_auth_login.js`
=> [fix] show error message when logining in

AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
https//github.com/digi-serve/planning/issues/530
=> Fix pull custom index value of connect field in record rule

AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
Fixed the underlying issue in digi-serve/appbuilder_class_core#76 so can revert changes in #78.
=> Revert #78 and fix in Core

AppBuilder/platform/dataFields/ABFieldDate.js, AppBuilder/platform/dataFields/ABFieldDateTime.js, init/Bootstrap.js, js/webix/locales/th-TH.js, ui/ClassUIPage.js
adds support for BE dates digi-serve/cars_app#49
=> use webix locales to display dates

AppBuilder/platform/ABObject.js
https://github.com/digi-serve/cars_app/issues/51
=> Add No Item Reported label

AppBuilder/platform/views/ABViewDetailComponent.js
https://github.com/digi-serve/cars_app/issues/56
=> *Fix display username in detail and data view widgets

AppBuilder/platform/views/ABViewDataview.js, AppBuilder/platform/views/viewComponent/ABViewDataviewComponent.js, AppBuilder/platform/views/viewComponent/ABViewDetailItemComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/46
=> Migrate dataview widget

AppBuilder/platform/views/ABViewConditionalContainer.js
The child components of a conditional were not being initialized
=> fix initializing if/else containers within conditional container

AppBuilder/platform/ABObject.js
user the refactored isUUID function
=> fix use new isUUID function

AppBuilder/platform/views/ABViewGrid.js, AppBuilder/platform/views/ABViewGridPopupSortFields.js
https://github.com/digi-serve/ns_app/issues/91 [Issue 8]
=> *Fix sort feature in Grid widget

styles/ui.css, ui/portal_work_user_profile_window.js
This changes the layout to look like this.
=> update to profile window

AppBuilder/platform/views/ABViewGrid.js
I noticed my pushes yesterday caused a bug when you are not editing existing settings
=> if we do not have local settings we need to get the current ones

ui/portal_work.js
Fixes problem loading Access Managed pages. Found in NS App Budgeting page.
=> fix loading pages a user has access to

AppBuilder/platform/RowUpdater.js, AppBuilder/platform/dataFields/ABFieldConnect.js, AppBuilder/platform/views/ABViewFormConnect.js
https://github.com/digi-serve/ns_app/issues/153
=> *Fix connect field in the mass updater

AppBuilder/platform/views/ABViewCSVImporter.js
https://github.com/digi-serve/ns_app/issues/123
=> *Fix undefined error

AppBuilder/platform/FilterComplex.js
https://github.com/digi-serve/ns_app/issues/147
=> *Fix is_empty and is_not_empty

AppBuilder/platform/RowUpdater.js, AppBuilder/platform/dataFields/ABFieldConnect.js, AppBuilder/platform/views/ABViewCSVImporter.js
https://github.com/digi-serve/ns_app/issues/154
For multiselect still does not work.
I don't sure webix supports those feature.
https://snippet.webix.com/gallery/core/5d3e8e0d
=> Fix filter and edit data in the object grid.

AppBuilder/platform/dataFields/ABFieldConnect.js
https://github.com/digi-serve/ab_platform_web/pull/178
=> *Load connect field options on demand

AppBuilder/platform/dataFields/ABFieldConnect.js
https://github.com/digi-serve/ab_platform_web/pull/178
=> *Prevent repeatly populate connect field data on Grid

AppBuilder/platform/dataFields/ABFieldConnect.js
https://github.com/digi-serve/ns_app/issues/154
=> *Update option list when linked data changes

AppBuilder/platform/FilterComplex.js
https://github.com/digi-serve/ab_platform_web/issues/183
=> *Fix filter by date in FilterComplex

AppBuilder/platform/views/ABViewGridPopupExport.js
https://github.com/digi-serve/ns_app/issues/173
=> +Export checked items in the Grid widget

AppBuilder/platform/RowUpdater.js
https://github.com/digi-serve/ns_app/issues/175
=> *Fix mass update values

ABDesigner/ab_work_object_workspace_popupMassUpdate.js, AppBuilder/platform/RowUpdater.js, AppBuilder/platform/views/ABViewGridPopupMassUpdate.js
https://github.com/digi-serve/ns_app/issues/181
=> +Add loading cursor to the mass update popup

AppBuilder/platform/RowUpdater.js, AppBuilder/platform/dataFields/ABFieldUser.js
https://github.com/digi-serve/ns_app/issues/181
=> *Fix set current user to the mass update popup

config/Config.js, init/initConfig.js
We used to send some settings on the div in `index.html`. Since it change to a static file reset password no longer works. (It just logs in the user without prompting for a new password).  Hotfix send the settings with `/config`
=> hotfix: fix reset password

init/Bootstrap.js, init/initDefinitions.js, resources/Tenant.js
This fixes the `NS V2 Bug: Login Error` task
=> [fix] prevent javascript crash during login sequence with invalid data.

AppBuilder/platform/views/viewComponent/ABViewDetailConnectComponent.js, resources/Multilingual.js
Handling network errors and preventing an error during DetailConnectComponent's onAfterRender()
=> Various Bug Fixes

AppBuilder/platform/ql/ABQL.js, AppBuilder/platform/views/ABViewFormConnect.js, AppBuilder/platform/views/ABViewGrid.js, AppBuilder/platform/views/viewComponent/ABViewDataviewComponent.js, AppBuilder/platform/views/viewComponent/ABViewFormCustomComponent.js, AppBuilder/platform/views/viewProperties/ABViewPropertyFilterData.js
:1234: 
https://github.com/digi-serve/plugin_ABDesigner/issues/117
https://github.com/digi-serve/plugin_ABDesigner/issues/99#issuecomment-1371687045
https://github.com/digi-serve/plugin_ABDesigner/issues/120
=> Fix those things

AppBuilder/ABFactory.js, AppBuilder/platform/FilterComplex.js, AppBuilder/platform/dataFields/ABFieldDate.js, AppBuilder/platform/dataFields/ABFieldDateTime.js, AppBuilder/platform/views/ABViewReportsManager.js, AppBuilder/platform/views/viewComponent/ABViewCSVImporterComponent.js
https://github.com/digi-serve/ab_service_process_manager/issues/39
=> *Fix .toDate consistency

AppBuilder/platform/views/ABViewFormConnect.js, AppBuilder/platform/views/viewComponent/ABViewCSVImporterComponent.js, AppBuilder/platform/views/viewProperties/ABViewPropertyAddPage.js, AppBuilder/platform/views/viewProperties/ABViewPropertyEditPage.js
https://github.com/digi-serve/ns_app/issues/194
=> form popup fixes

AppBuilder/platform/views/ABViewForm.js, AppBuilder/platform/views/ABViewFormConnect.js, AppBuilder/platform/views/ABViewPage.js, AppBuilder/platform/views/viewComponent/ABViewContainerComponent.js, AppBuilder/platform/views/viewComponent/ABViewFormButtonComponent.js, AppBuilder/platform/views/viewComponent/ABViewFormComponent.js, AppBuilder/platform/views/viewComponent/ABViewFormCustomComponent.js, AppBuilder/platform/views/viewProperties/ABViewPropertyAddPage.js, AppBuilder/platform/views/viewProperties/ABViewPropertyEditPage.js
Callbacks are tweaked just enough to make things work as expected: _logic is NOT removed
https://github.com/digi-serve/ns_app/issues/194
=> [fix] add new form/edit existing popups

AppBuilder/platform/views/viewComponent/ABViewFormCustomComponent.js
The code causing the errors that went up last week came back so I am guessing we need the alternate case in a place I have not tested...this code supports both cases and hopefully will prevent errors from being fired.
=> fix errors that prevent clicking upload image field

AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/139
=> *Fix filter options of the connect element in the form widget

AppBuilder/platform/ql/ABQL.js, AppBuilder/platform/ql/ABQLManager.js
https://github.com/digi-serve/plugin_ABDesigner/issues/136
=> *Fix populate the next QL when select field option

AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js
https://github.com/digi-serve/ns_app/issues/194
=> *Fix plus button in the form widget

AppBuilder/platform/dataFields/ABFieldConnect.js, AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js
https://github.com/digi-serve/ns_app/issues/194
https://github.com/digi-serve/ab_platform_web/pull/243
=> *Fix pull data after new one get added

AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js, AppBuilder/platform/views/viewComponent/ABViewFormCustomComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/133
=> *Fix UI of elements when set require option

AppBuilder/platform/RowUpdater.js
https://github.com/digi-serve/plugin_ABDesigner/issues/168
=> *Fix set the "Current Date/Time" check box

AppBuilder/platform/process/tasks/ABProcessTaskUserExternal.js, resources/NetworkRestSocket.js, ui/portal_work_inbox.js
Add event ab.inbox.update for ProcessTaskUserExternal.
=> Enhancement

AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
https://github.com/digi-serve/ns_app/issues/223
=> *Fix Update Connected Record

AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
https://github.com/digi-serve/ns_app/issues/229
=> *Fix pull ABField in the record rule updater

AppBuilder/platform/views/viewComponent/ABViewPivotComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/179
=> *Fix pivot widget

AppBuilder/platform/dataFields/ABFieldImage.js, AppBuilder/platform/views/ABViewKanbanFormSidePanel.js, AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js, AppBuilder/platform/views/viewComponent/ABViewKanbanComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/178
=> Implement detail & form page links to Kanban widget

AppBuilder/platform/ABDataCollection.js
https://github.com/digi-serve/ns_app/issues/238
=> *Fix filter of DC when cursor of parent DC is updated

AppBuilder/platform/views/viewComponent/ABViewDetailComponent.js
https://github.com/digi-serve/ns_app/issues/261
=> *Fix display data of Formula field in detail widget

AppBuilder/platform/views/ABViewForm.js
https://github.com/digi-serve/ns_app/issues/268
https://github.com/digi-serve/ns_app/issues/264
=> *Fix pull Calculate & Formula field values in Form widget

ui/portal_auth_login_form.js
This fixes one of the errors that leaves the UI in the "Hello" bug state.
=> [fix] one more cause of the Hello bug

ui/portal_access_level_manager.js
https://github.com/digi-serve/ns_app/issues/271
=> *Fix update "No Access" option

ui/portal_auth_login_form.js, ui/portal_auth_login_resetRequest.js
=> [fix] Found another place where invalid config data prevents the UI login screen

AppBuilder/platform/views/viewComponent/ABViewDataviewComponent.js
https://github.com/digi-serve/ab_platform_web/issues/342
=> *Apply webix.datatable to ABDataView widget

AppBuilder/platform/views/viewComponent/ABViewReportsManagerComponent.js
Fix bugs date filter, datetime display and connected field.
=> Fix bugs date filter and connected field

AppBuilder/platform/views/ABViewPDFImporter.js, AppBuilder/platform/views/viewComponent/ABViewPDFImporterComponent.js, package-lock.json, package.json, styles/ui.css, webpack.common.js
https://github.com/digi-serve/ns_app/issues/179
=> PDF Importer widget

AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js, AppBuilder/platform/views/viewComponent/ABViewPDFImporterComponent.js, AppBuilder/platform/views/viewComponent/ABViewTabComponent.js, AppBuilder/platform/views/viewProperties/ABViewPropertyAddPage.js
https://github.com/digi-serve/ns_app/issues/179
=> *Apply PDF importer widget to able to be a popup of connect field in the Form widget

AppBuilder/platform/views/viewComponent/ABViewPDFImporterComponent.js
https://github.com/digi-serve/ns_app/issues/179
=> Add the submit rule feature to the PDF Importer widget

AppBuilder/platform/views/viewComponent/ABViewDataviewComponent.js, AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/204
=> *Improve load data of DC who are used on record rules of the Form widget

AppBuilder/platform/views/viewComponent/ABViewReportsManagerComponent.js, AppBuilder/platform/views/viewComponent/ABViewSchedulerComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/204
=> *Improve loading order of Scheduler widget who are in the Tab widget

AppBuilder/ABFactory.js, index.js, init/Bootstrap.js, init/sentry.js, package-lock.json, package.json, webpack.dev.js, webpack.prod.js
=> Setup sentry tracking

AppBuilder/platform/views/viewComponent/ABViewPivotComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/206
=> *Migrate pivot widget of webix 10

AppBuilder/platform/dataFields/ABFieldConnect.js
- Fix bug the undefined "val" parameter.
=> Fix bug undefined "val"

.github/workflows/pr-merge-release.yml
- Automate Build, Version and Release
=> fix remove invalid dependant job

.github/workflows/dispatch-web-update.yml
- Automate Build, Version and Release
=> fix remove invalid job dependency

.github/workflows/dispatch-web-update.yml, .github/workflows/pr-merge-release.yml, .github/workflows/update-core-version.yml
=> fix pass in token

AppBuilder/platform/ABModelApi.js, AppBuilder/platform/ABObjectApi.js
https://github.com/digi-serve/ab_service_appbuilder/issues/55
https://github.com/digi-serve/ab_service_appbuilder/issues/56
- Read data to a shadow table.
=> Read data to a shadow table

AppBuilder/platform/views/viewComponent/ABViewComponent.js, AppBuilder/platform/views/viewComponent/ABViewReportsManagerComponent.js, AppBuilder/platform/views/viewComponent/ABViewSchedulerComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/210
- Fixed bugs where some Scheduler views were not displaying data.
=> Some Scheduler views are not displaying data

ui/portal_work.js
https://github.com/digi-serve/ns_app/issues/314
- Add role filters to application menu list
=> *Add filter to application menu list

AppBuilder/platform/views/ABViewForm.js
- Fix multilingual bug https://github.com/digi-serve/cars_app/issues/120
=> Fix multilingual bug

AppBuilder/platform/dataFields/ABFieldImage.js, AppBuilder/platform/views/viewComponent/ABViewFormCustomComponent.js, styles/ui.css
- fix layout issues of image upload and image view inside of forms and grids
=> fix display of image upload after webix upgrade

AppBuilder/platform/dataFields/ABFieldConnect.js
https://github.com/digi-serve/ns_app/issues/322
- Fix select the option of Connect field that use custom index in the Form widget
=> *Fix select option of Connect field that use custom index

AppBuilder/platform/dataFields/ABFieldConnect.js
https://github.com/digi-serve/ns_app/issues/322
- Fix selected value of "Filter by Connected" when parent options does not be loaded completely
=> *Fix value of "Filter by Connected" when parent options are loading

AppBuilder/platform/ABModelApi.js, AppBuilder/platform/ABObjectApi.js
- Fetch data of API obect from back-end
=> *Fetch data of API obect from back-end

AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/221
- Fix display the delete confirm popup twice
=> *Add code to prevent show the confirm popup twice

AppBuilder/platform/views/viewComponent/ABViewCarouselComponent.js
https://github.com/digi-serve/ns_app/issues/323
- lazy load carousel image
=> Carousel load

ui/portal_access_level_manager.js
https://github.com/digi-serve/ns_app/issues/316
- Add the warning message when the role is a role access level
=> +Add the warning message when the role is a role access level

AppBuilder/platform/views/viewComponent/ABViewDataviewComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/219
- Fix width of item in the Dataview widget
=> *Fix width of item in the Dataview widget

AppBuilder/platform/dataFields/ABFieldImage.js, AppBuilder/platform/views/ABViewForm.js
- Show an upload progress bar when adding an image
- Require an image to be finished uploading before submitting a form
- Fix issue where validation errors found by webix were not shown
=> Improve image upload ui

AppBuilder/platform/ABDataCollection.js
https://github.com/digi-serve/ns_app/issues/338
- Fix filter data by cursor of the parent DC
=> *Fix filter data by cursor of the parent DC

AppBuilder/platform/views/viewComponent/ABViewPivotComponent.js
https://github.com/digi-serve/ns_app/issues/334
- fix: pivot displays using it's decimal place setting.
=> fix pivot decimal place setting

AppBuilder/platform/ql/ABQL.js
https://github.com/digi-serve/ns_app/issues/332
- Fix clear filter complex when setting is empty
=> Fix clear filter complex when setting is empty

AppBuilder/platform/views/viewComponent/ABViewPDFImporterComponent.js
https://github.com/digi-serve/ns_app/issues/345
- Set select PDF images by default in PDF Importer widget
=> *Set select PDF images by default in PDF Importer widget

AppBuilder/platform/dataFields/ABFieldConnect.js
- Update each options have own throttle to pull data
=> *Update each options have own throttle to pull data

AppBuilder/platform/views/viewComponent/ABViewGridComponent.js, AppBuilder/platform/views/viewProperties/ABViewPropertyLinkPage.js
- Update DC triggers when change the page
=> *Update DC triggers when change the page

ui/portal_auth_login_form.js
https://github.com/digi-serve/ab_service_tenant_manager/issues/48
🗒️ Test `0001_portal_auth_login` will fail - requires digi-serve/ab_runtime#236
- Remove the tenant select on login
=> Remove tenant dropdown list

ui/portal_work_user_qr_window.js
https://github.com/digi-serve/sdc-app/issues/61
- Fix QR Code for Relay is Cut off
=> *Fix QR Code for Relay is Cut off

AppBuilder/platform/ABHint.js, AppBuilder/platform/views/viewComponent/ABViewTabComponent.js, resources/NetworkRest.js
- Fix/Catch Errors reported by Sentry:
-  [APPBUILDER-WEB-1A0](https://appdev-designs.sentry.io/issues/4631381210/)
- [APPBUILDER-WEB-1BN](https://appdev-designs.sentry.io/issues/4687690263/)
- [APPBUILDER-WEB-XV](https://appdev-designs.sentry.io/issues/4514863163/)
=> Fix Errors reported by Sentry

AppBuilder/platform/views/viewComponent/ABViewDataviewComponent.js
https://github.com/digi-serve/ns_app/issues/351
- Fix resizing of Dataview widget
=> Fix resizing of Dataview widget

AppBuilder/platform/views/viewComponent/ABViewDetailItemComponent.js
https://github.com/digi-serve/ns_app/issues/359
- Fix display safe html tags in the Detail widget
=> *Fix display safe html tags in the Detail widget

AppBuilder/platform/FilterComplex.js, AppBuilder/platform/views/viewComponent/ABViewMenuComponent.js, AppBuilder/platform/views/viewComponent/ABViewTabComponent.js, resources/NetworkRestSocket.js
- fix unhandled errors reported in Sentry:
- [APPBUILDER-WEB-YD](https://appdev-designs.sentry.io/issues/4533828541/)
- [APPBUILDER-WEB-1H9](https://appdev-designs.sentry.io/issues/4769183057/)
- [APPBUILDER-WEB-1EE](https://appdev-designs.sentry.io/issues/4734863531/)
- [APPBUILDER-WEB-1FC](https://appdev-designs.sentry.io/issues/4743392248/)
=> Fix unhandled errors reported in Sentry

AppBuilder/platform/dataFields/ABFieldConnect.js, AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js
- [fix] prevent missing form item errors
Addresses Sentry Issue: [APPBUILDER-WEB-12N](https://appdev-designs.sentry.io/issues/4542628902/)
=> [fix] prevent missing form item errors

.github/workflows/lighthouse.yml
Lighthouse workflow will now send reports to https://lighthouse.digiserve.org
=> Adjust lighthouse workflow for lhci server

AppBuilder/platform/views/viewComponent/ABViewPDFImporterComponent.js, init/pdfjs.js
https://github.com/digi-serve/ab_platform_web/pull/429#issuecomment-1882582123
- Fix load PDF library files
=> *Fix load PDF library files

AppBuilder/platform/ABObject.js
https://team.digiserve.org/main/pl/e19y76x1npg1dpp5orrxaq3nqh
- Fix the query workspace page
=> *Fix the query workspace page

index.js, init/sailsIo.js, package-lock.json, package.json, webpack.common.js, webpack/index.ejs
- include sailsio via webpack so we can minimize/compress it
=> include sailsio via webpack so we can minimize/compress it

webix_custom_components/formioPreview.js
- fix problem displaying inbox task data
=> fix loading data into formio for inbox tasks

AppBuilder/platform/FilterComplex.js
https://github.com/digi-serve/ns_app/issues/384
- Add "checked" and "unchecked" filter conditions
=> +Add "checked" and "unchecked" filter conditions

AppBuilder/platform/views/ABViewForm.js, AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
https://github.com/digi-serve/ns_app/issues/388
- *Fix disable the save button in the form widget
=> *Fix disable the save button

AppBuilder/platform/dataFields/ABFieldImage.js, AppBuilder/platform/views/viewComponent/ABViewCarouselComponent.js
https://github.com/digi-serve/ns_app/issues/212
- Add rotate icon buttons to Carousel widget
=> +Add rotate icon buttons to Carousel widget

AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
https://github.com/digi-serve/planning/issues/507
- Implement Current Date option to the record rule
=> *Implement Current Date option to the record rule

AppBuilder/platform/ABObject.js
https://github.com/digi-serve/plugin_ABDesigner/issues/7
- Implement Object information
=> Implement Object information

AppBuilder/platform/dataFields/ABField.js
https://github.com/digi-serve/plugin_ABDesigner/issues/6
- Add get field information endpoint
=> +Add get field information endpoint

AppBuilder/platform/views/viewComponent/ABViewCarouselComponent.js
https://github.com/digi-serve/planning/issues/399
- Implement zoom in/out in the carousel widget
=> *Implement zoom in/out in the carousel widget

AppBuilder/platform/views/ABViewForm.js, AppBuilder/platform/views/viewComponent/ABViewFormButtonComponent.js
https://github.com/digi-serve/ns_app/issues/89
- Add delete feature to the Form widget
=> +Add delete feature to the Form widget

AppBuilder/platform/dataFields/ABField.js, AppBuilder/platform/views/viewComponent/ABViewFormButtonComponent.js
https://github.com/digi-serve/ns_app/issues/409
- Fix populate value to the datepicker
Error `.getTime is not a function at e.G1 (radio.js:144:26)`
=> *Fix populate value to the datepicker

config/Config.js, styles/ui.css, ui/portal_auth_login_form.js, ui/portal_work.js
https://github.com/digi-serve/ab_platform_web/issues/403
- display a link to a privacy policy
=> Show Privacy Policy Link

init/initUser.js, ui/portal_work.js, ui/portal_work_user_profile_window.js, ui/portal_work_user_switcheroo.js
- fix an error setting the real user in config (when switcherood)
- add `data-cy` attributes to allow testing switcheroo
=> Fix switcheroo and add cy hooks

AppBuilder/platform/views/viewComponent/ABViewCSVExporterComponent.js
https://github.com/digi-serve/ns_app/issues/416
- Fix filter of CSV Exporter widget
=> *Fix filter of CSV Exporter widget

AppBuilder/platform/dataFields/ABFieldConnect.js, AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
https://github.com/digi-serve/ab_platform_web/issues/468
- Fix populate M:1 connect option
=> *Fix populate M:1 connect option

AppBuilder/platform/ABComponent.js
[APPBUILDER-WEB-1Z9](https://appdev-designs.sentry.io/issues/5086050233/)
- fix an uncaught error reported in Sentry ([APPBUILDER-WEB-1Z9](https://appdev-designs.sentry.io/issues/5086050233/))
Unsure how to reproduce
=> Fix calling uid on undefined

AppBuilder/platform/views/ABViewGridPopupMassUpdate.js
https://github.com/digi-serve/ns_app/issues/404
- Update items in the grid when mass updating
=> *Update items in the grid when mass updating

AppBuilder/platform/ABDataCollection.js, resources/NetworkRestSocket.js
NOTE: I'd like to merge this in with our #master as well as whatever branch is currently on `production` so I can compare the two.
This is also designed to work with the same [PR](https://github.com/digi-serve/ab_service_appbuilder/pull/89) in `appbuilder`.
- [wip] some temporary logs to help me identify the impact of our socket communications
- [wip] simplify the datacollection trigger setup.
=> Some Temporary logs to help me gauge the impact of our socket communications.

ui/portal_work.js
https://github.com/digi-serve/ns_app/issues/430
- Add loading cursor to switcheroo to let users know the progress
=> +Add loading cursor to switcheroo to let users know the progress

AppBuilder/ABFactory.js, AppBuilder/platform/ABObjectApi.js, AppBuilder/platform/dataFields/ABFieldConnect.js, AppBuilder/platform/views/viewComponent/ABViewDetailCustomComponent.js, AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js, AppBuilder/platform/views/viewComponent/ABViewFormDatepickerComponent.js, AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
- fix CodeQL Warnings:
- https://github.com/digi-serve/ab_platform_web/security/code-scanning/576
- https://github.com/digi-serve/ab_platform_web/security/code-scanning/552
- https://github.com/digi-serve/ab_platform_web/security/code-scanning/490
- https://github.com/digi-serve/ab_platform_web/security/code-scanning/491
- https://github.com/digi-serve/ab_platform_web/security/code-scanning/59
- https://github.com/digi-serve/ab_platform_web/security/code-scanning/61
- https://github.com/digi-serve/ab_platform_web/security/code-scanning/422
- https://github.com/digi-serve/ab_platform_web/security/code-scanning/566
behavior should be covered in existing tests
=> Fixes to CodeQL warnings

AppBuilder/platform/dataFields/ABFieldJson.js, resources/NetworkRestSocket.js
- [add] additional logging info on incoming sockets
- [fix] prevent error when web ui item not found
=> Additional Logging Info and quick fix

package-lock.json, package.json
- fix an issue where the rich text editor was not displayed
No tests coverage yet. Will add a test later.
=> Downgrade tinymce dependency

AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/242
- Fix submit empty value when connect field data does not load completely
I'm designing how to test it in E2E because this issue happens when load data slowly.
It should be covered by a test case.
=> *Fix submit empty value when connect field data does not load completely

AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
https://github.com/digi-serve/plugin_ABDesigner/issues/242
- Fix populate option with empty connect value
It should have a test case to cover for https://github.com/digi-serve/ab_platform_web/pull/504
=> *Fix populate option with empty connect value

AppBuilder/platform/views/ABViewGridPopupSortFields.js
=> Fix this.AB is undefined

AppBuilder/platform/views/ABViewGridPopupSortFields.js
=> *Fix this.AB is undefined

AppBuilder/platform/views/ABViewGridPopupSortFields.js
https://github.com/digi-serve/ab_platform_web/issues/471
- Fix use global.AB variable in E2E testing
We have already
=> *Fix use global.AB variable in E2E testing

AppBuilder/platform/FilterComplex.js, AppBuilder/platform/RowFilter.js
=> Current date filter

ui/ClassUIPage.js
- [fix] prevent an error when accessing a missing ui component.
Fixing a bug caught on running site.  No test created for this.
=> Prevent an error when UI component isn't present in DOM

AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js
- Fix pull value of the record rule option
=> *Fix pull value of the record rule option

AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js, package-lock.json, package.json, webpack.dev.js, webpack.prod.js
- Insert images proportionally into DocX templates.
=> Insert images with proper proportions in DocX templates.

AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
- Include related data in final results set.
=> Use the related object and not just the UUID.

AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
- Support user filters being used when downloading a DocX report.
=> Support user filters in DocX reports.

AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
- Upgrade data fetch to include latest features. (Including: Follow Cursor, Selected Cursor, User Filters and User Sorts)
=> Upgrade data fetch to include latest features.

AppBuilder/platform/views/viewComponent/ABViewContainerComponent.js, AppBuilder/platform/views/viewComponent/ABViewDataviewComponent.js
- Add Dataview height
- Set Dataview xCount
- Adjust dx, dy
=> Fix Dataview component width.

AppBuilder/platform/FilterComplex.js
https://github.com/digi-serve/ns_app/issues/490
- Fix options of "By Query Field"
=> Fix options of "By Query Field"

AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
-  Check max length on grid and alert when over the limit.
- [#393](https://github.com/digi-serve/planning/issues/393)
=> Limit the maximum length of text field

AppBuilder/ABFactory.js, AppBuilder/platform/ABModel.js, AppBuilder/platform/FilterComplex.js
- function getCurrentDateValue()
=> Fix "is current date" filter in Data Collections

AppBuilder/platform/ABModel.js, init/initConfig.js, ui/portal_auth_login_form.js, ui/portal_auth_login_resetPassword.js, ui/portal_auth_login_resetRequest.js
Fixes issue: #555
Related PR: https://github.com/digi-serve/ab_service_api_sails/pull/171 
- read settings from `/settings` route
Tests to be added in https://github.com/digi-serve/ab_runtime/pull/401
=> Fix reset password

.github/workflows/e2e-tests.yml
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions
https://github.com/digi-serve/ab_platform_web/actions/runs/10917722855/job/30301610543
- Upgrade actions/upload-artifact to version 4
=> Upgrade actions/upload-artifact

.github/workflows/e2e-tests.yml, AppBuilder/platform/views/viewComponent/ABViewPDFImporterComponent.js
https://github.com/digi-serve/ns_app/issues/515
- Increases width of the saving image from PDF Importer widget
=> Increases width of the saving image from PDF Importer widget

AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
Simple patch for preventing an error when a DataTable isn't returned.
- [fix] for when a DataTable is not found.
none
=> Fix no DataTable

AppBuilder/platform/views/viewComponent/ABViewGridComponent.js, AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/team-widget.css, test/AppBuilder/platform/views/viewComponent/ABViewOrgChartTeams.test.js
https://github.com/digi-serve/ab_platform_web/issues/562
- Strategy field on team in add / edit form
- Color team nodes based on strategy 
- Updated unit tests
Related: 
https://github.com/digi-serve/appbuilder_class_core/pull/254
https://github.com/digi-serve/plugin_ABDesigner/pull/264
=> Team Nodes styled by strategy

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/team-widget.css, test/AppBuilder/platform/views/viewComponent/ABViewOrgChartTeams.test.js
https://github.com/digi-serve/ab_platform_web/issues/573
- add filter for team name, status
- add option to display inactive teams
- apply strategy color on add/edit team
Updated unit tests
=> Filter teams in team chart

AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
https://github.com/digi-serve/ab_platform_web/issues/578
- fix error applying local formatting to dates in form
=> Fix error applying local formatting to dates in form

AppBuilder/platform/FilterComplex.js, AppBuilder/platform/dataFields/ABFieldList.js, AppBuilder/platform/views/viewComponent/ABViewDataviewComponent.js, resources/NetworkRestSocket.js
Fix sentry type errors:
- [APPBUILDER-WEB-1M0](https://appdev-designs.sentry.io/issues/4904347622/)
- [APPBUILDER-WEB-25E](https://appdev-designs.sentry.io/issues/5343008152/)
- [APPBUILDER-WEB-2ED](https://appdev-designs.sentry.io/issues/6016419585/)
- [APPBUILDER-WEB-2CK](https://appdev-designs.sentry.io/issues/5834834957/)
- fix type errors
=> Fix type errors found in sentry

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
- https://github.com/digi-serve/ab_platform_web/issues/559
=> Team Widget can edit assignments

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/team-widget.css
- Fix extra rendering node bug and prevent droping nodes in content area
=> Fix extra rendering node bug and prevent droping nodes in content area

AppBuilder/platform/views/ABViewDataSelect.js, AppBuilder/platform/views/viewComponent/ABViewDataSelectComponent.js
Needed for https://github.com/digi-serve/planning/issues/578
Other PRs:
https://github.com/digi-serve/appbuilder_class_core/pull/268
https://github.com/digi-serve/plugin_ABDesigner/pull/276
- Add widget to set cursor in a Datacollection
=> Add widget to set cursor in a Datacollection

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
https://github.com/digi-serve/planning/issues/578
Entity is a required field on all creates in NetSuite
- reload the widget when the entity changes
- attach entity id to team and assignment creates
=> Add entity and attach to creates

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/team-widget.css
- https://github.com/digi-serve/ab_platform_web/issues/561
- https://github.com/digi-serve/ab_platform_web/issues/574
=> Content mapping data and filter

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/team-widget.css
- Add start date and end date fields.
=> Add start date and end date fields

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/team-widget.css
- Fix display 1 - 4 are for Image, Job Title, Firstname and Lastname.
- Assignment border depends on a team strategy solor.
- Other UIs adjustment.
=> UI improvements

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
https://github.com/digi-serve/global-hr-update/issues/196
- Fix label and fix limit edit form's fields
- Fix data type after submission.
=> Fix label and fix limit edit form's fields

AppBuilder/platform/dataFields/ABFieldConnect.js, AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/team-widget.css
https://github.com/digi-serve/planning/issues/580
- Filter Strategy Options by Entity
- Use the Sub Strategy Code in the Strategy Option label
- Update Form UI to match the widget
- Prevent submitting the form if incomplete
=> Enhance Team Edit Form

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/team-widget.css
- fix filter by strategy and cleanup filter ui
=> fix filter by strategy and cleanup filter ui

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
=> Still get undefined columns

AppBuilder/platform/views/viewComponent/ABViewDataSelectComponent.js, AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
- Fix bug typo and some performance improvements.
=> Fix bug typo and some performance improvements

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/team-widget.css
- Performance and data panel load improvement.
=> Performance and data panel load improvement

AppBuilder/platform/FilterComplex.js
- Fix the display of conditions in filter complex (display the rule, format dates)
=> Fix filter display conditions

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
- Optimize and fix paging bugs, the entity cursor.
- Refactor the filter feature
=> Optimize,  fix bugs and new UI issues.

AppBuilder/platform/FilterComplex.js
Caused by https://github.com/digi-serve/ab_platform_web/pull/609
- fix populating filter complex ui with in query filters
=> Fix populating filter complex ui with in query filters

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/orgchart-webcomponents.css
- Fix the typo bug.
- End Date validation.
- Form type convertion.
- Warning popup.
=> UI improvement

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
- Fix the new data panel list render bugs.
=> Fix the new data panel list render bugs

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
=> Hide inactive data

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
- Fix empty chartData error.
- Change data panel filter by tab label -> tab index.
- Hot fix for lost data DC.
=> Fix UI bugs

AppBuilder/platform/views/viewComponent/ABViewDataSelectComponent.js
- sort data select options alphabetically
- switch to combo so can type
=> Sort the data select

AppBuilder/platform/views/viewComponent/ABViewDataviewComponent.js
https://github.com/digi-serve/ns_app/issues/557
- Show refresh button when there is a new data in Dataview widget
=> +Show refresh button when there is a new data

AppBuilder/platform/FilterComplex.js
from https://github.com/digi-serve/plugin_ABDesigner/issues/263
-  Except convert days to date when filter is last...days
=> last...days filter not working

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/team-widget.css
https://github.com/digi-serve/global-hr-update/issues/198
- resize buttons and data panels when the page size changes
=> fix respond to window resize

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js, styles/team-widget.css
- https://docs.google.com/document/d/1hSM_3YT6Cu3t2Pc2kbOiXGSgr-qW16NtdRe2sp5q4tk/edit?tab=t.0#heading=h.x8z7eglc99uo. the feature fixes (The trashcan feature here is wrong but I have finished. I will follow the new https://docs.google.com/spreadsheets/d/1IKp1V-5GFofCFDueBFuBgJl7lcmQVCyUZDSBXrGQ-v8/edit?gid=0#gid=0 after this).
- Optimize things and fix bugs.
=> UI fixes, optimize things and fix bugs

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
- Finish https://docs.google.com/spreadsheets/d/1IKp1V-5GFofCFDueBFuBgJl7lcmQVCyUZDSBXrGQ-v8/edit?gid=0#gid=0.
- Some bugs fix and optimize.
=> Design doc UI

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
- Fix the bug the data panal record does not exist while paging.
=> Fix the bug the data panal record does not exist while paging

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
- Fix the team delete logic if there are any assignments ever.
=> Fix the team delete logic if there are any assignments ever

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
- Prevent drop assignment with same employees from team to team.
=> Prevent drop assignment with same employees from team to team

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
- Fix bug dropping assignment to leader/member in the same team.
=> Fix bug dropping assignment to leader/member in the same team

AppBuilder/platform/ql/ABQL.js, AppBuilder/platform/ql/ABQLManager.js
- fix wrong next QL ops in process designer
=> Fix to Query task operations

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
- To simplify UX Strategy is now input as two drop downs: strategy code, then sub strategy code
=> Refactor team strategy input as 2 drop downs

AppBuilder/platform/dataFields/ABFieldConnect.js
=> Miss the populate param

AppBuilder/platform/process/tasks/ABProcessTaskUserForm.js, resources/NetworkRestSocket.js, ui/portal_work.js, ui/portal_work_task_user_form.js, webix_custom_components/formioBuilder.js, webix_custom_components/formioPreview.js
- https://github.com/digi-serve/global-hr-update/issues/219
=> Implement the user form task

AppBuilder/platform/ABModel.js, resources/Network.js, resources/NetworkRest.js
These are various fixes and changes made to the PWA platform that are also relevant to our WEB platform
- [fix] various updates made on pwa platform and pulled over here
=> Synchronize updates made to PWA platform

AppBuilder/platform/process/tasks/ABProcessGatewayExclusive.js, ui/portal_auth_login_resetRequest.js, webix_custom_components/formioBuilder.js
- Prevent undefined filterValue.
- Form builder now can get ProcessTaskUserForm values.
=> Fix bug missing value

AppBuilder/platform/ABObjectApi.js, AppBuilder/platform/ABProcess.js, AppBuilder/platform/process/tasks/ABProcessTaskServiceApi.js, AppBuilder/platform/process/tasks/ABProcessTaskServiceCalculate.js
- Add API Request Service task to processes
- Fix duplicate calls to save process elements
No test yet, tested locally.
📝 Not Feature Complete, but enough functionality for webhooks
=> Add an API Request Service task to processes

ui/portal_work_task_user_form.js
- Catching error for showing popup
=> Catching error for showing popup

.github/workflows/pr-merge-release.yml
```
[Invalid workflow file: .github/workflows/pr-merge-release.yml#L36](https://github.com/CruGlobal/ab_platform_web/actions/runs/16133696241/workflow)
error parsing called workflow
".github/workflows/pr-merge-release.yml"
-> "CruGlobal/.github/.github/workflows/dispatch-update.yml@master"
: failed to fetch workflow: reference to workflow should be either a valid branch, tag, or commit
```
https://github.com/CruGlobal/.github/blob/main/.github/workflows/docker-build.yml
https://github.com/CruGlobal/.github/blob/main/.github/workflows/dispatch-update.yml
=> master -> main Update pr-merge-release.yml

AppBuilder/platform/dataFields/ABFieldConnect.js
Enable Advance option for mobile
https://github.com/CruGlobal/appbuilder_platform_pwa/issues/18
=> Enable connect field on mobile

ui/portal_work_inbox_taskWindow.js
https://github.com/CruGlobal/global-hr-update/issues/299
=> *Make the 'Ask Other Entity HR to Approve' Window movable
