AppBuilder/platform/views/ABViewDataview.js

I added data-cy attributes to the dataview items using the record's id. This will be consistent for any test data we preload, but will not be consistent for records added during the tests. I also added a data-cy attribute to the layout container. We could use other cypress commands like [`children()`](https://docs.cypress.io/api/commands/children#Syntax) and [`eq()`](https://docs.cypress.io/api/commands/eq#Syntax) to get the correct item.
Alternatively I can change to just use the index of the item in the dataview but I'm not sure if the index will be the same each time.

Add Cypress data-cy attributes to dataviews

---

AppBuilder/platform/views/ABViewTab.js

Set id after render
POSSIBLE ISSUE:
Collapse/Expand options have their cy data set multiple times? I was unable to optimize this.

Vertical tab options, collapse/expand buttons have cyData

---

AppBuilder/platform/views/ABViewDetailCheckbox.js
AppBuilder/platform/views/ABViewDetailCustom.js
AppBuilder/platform/views/ABViewDetailImage.js
AppBuilder/platform/views/ABViewDetailSelectivity.js
AppBuilder/platform/views/ABViewDetailText.js

Because detail components in a dataview do not have a parent detail view.

Fix error when detail text in dataview doesn't have a parent detail

---

AppBuilder/platform/views/ABViewComment.js

Was using `Account.usersAll()`  should be `Account.userList`

fix comment widget loading users with Account._listUsers

---

AppBuilder/platform/views/ABViewGrid.js

NOTE: When height is 0 webix interprets that as auto height

When grid was refactored we left out the height settings.

---

AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js

Currently the record rule Update Record using Current Selection of a datacollection is not working.
Reported on the well app in production.
I found that the cursor is not set when the datacollection is cloned.

Hotfix: Record rule insert based on cursor.

---

config/Config.js
init/Bootstrap.js
init/initDefinitions.js

- Requests definition separate from config.
- Request the time server side definitions cache was changed
- Adds this time to the definitions request so that new definitions will be requested if the time is different form the browser cached request

Load and cache definitions as js

---

AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js

In v2 user field are also connections so need to make sure we only use the "ab-current-user" rule.

fix applying current user record rule

---

AppBuilder/platform/views/ABViewGridPopupExport.js

fixes 11.1 in https://github.com/digi-serve/ns_app/issues/91. Because idbase wasn't passed in properly, our webix ids were clashing

fix idbase in grid export popup

---

AppBuilder/platform/views/ABViewConditionalContainer.js

If the conditional container only tries to load on `loadData`, data collections which have complicated filters or have cursors set by other DCs will fail to load. (as seen in CARs Edit Child)
Only If there is NO data does line `116` `dv.dataStatusFlag` get checked.
I want to force this to run when there is no data, and in order to do that, the DC needs to be initialized
*critical for* https://github.com/digi-serve/cars_app/pull/76

[fix] Catch initialized data emit

---

AppBuilder/platform/views/ABViewConditionalContainer.js

The most important addition is that an `undefined` cursor will default to `Else` in a conditional container.
The use case for this is a data collection which becomes empty because of a parent link.
Welcoming ideas on how to do this better, as I have not solved that wrong data shows up when switching between `Children` in `CARs`
Ideally this should put a 'wait' on a conditional widget if the parent `Data Collection` gets changed.
There is, however, some lag for `Prelim Health Info`. Possibly because all DCs don't emit that they are un-initialized all at once?

[fix] if no cursor, default to ELSE, and don't load incorrect data

---

AppBuilder/platform/views/ABViewFormConnect.js

I need this because new definitions from dev.digiserve are dropping the filter conditions: if those filter conditions are empty V2 fails to load.
the ab.error should make it possible to hunt down later

[add] if no filterCon: error and create empty

---

AppBuilder/platform/views/ABViewConnectDataFilter.js
AppBuilder/platform/views/ABViewGrid.js

This is a new widget to filter a datacollection by a connected record field. This is needed for the Well, where many of their objects are best identified by Client (connected record). We don't currently have a simple way to filter using connected records.
This is a standalone widget that updates a datacollection, so it should work with other widgets. I considered adding it to the grid filters, but I find the current filters are already too complex and hard to understand. We probably need to redesign that. 
Not adding this to the Designer immediately, but we can add a definition manually. Only requires:
```JSON
"settings": {
"dataviewID": "e56df324-532d-4ac1-82f3-8e1df3a63328",
"field": "Clients",
},
```
Here's what it looks like:
Also changes core: …

Connected Data Filter Widget

---

AppBuilder/platform/views/ABViewConnectDataFilter.js
AppBuilder/platform/views/ABViewFormConnect.js

onShow gets called multiple times with typing, and we clear and load the options each time. This means filtering by text input doesn't work. We only need to load the options once. Also added a more flexible search, so that we can match any part of the label not just the start.
Should also do this on the grid editor, but it's a bit more complicated.

do not populate suggest options in onBeforeShow

---

init/initDiv.js

This fixes the issue where the menu bar would seemingly be loaded at the bottom of the screen. The issue is traced back to an issue with Webix and popups however the quick fix is to ensure that Webix is only rendering their content into the dimensions of the browser window with no scrolling. The addition of my preloader caused the initial screen to be slightly larger because of an invisible button that was also on the page. These CSS changes should force the preloader to just fit the window.

fix issue where menu was loaded at bottom of screen

---

AppBuilder/platform/dataFields/ABFieldList.js

I found the instance where I would click on a select list's clear button and it would not clear...it was because the select list was a required field. This fix will not include the clear button on select lists if they are required...you can still edit the entry just not allowed to clear it.
so this...
becomes this...

do not show clear button on required select lists

---

init/initConfig.js

Visiting `/home` directly (instead of `/`) causes an error authenticating with Okta and CAS. Probably better ways to fix this, but redirecting them to `/` when we get this error should work.

hotfix: okta/cas auth error when visiting /home directly

---

AppBuilder/platform/views/viewComponent/ABViewCSVImporterComponent.js

CsImporter need a label function, but we can't pass `this.label` directly as `this` will be undefined.
prevents opening app in ABDesigner

fix passing method as function to CsvImporter

---

AppBuilder/platform/dataFields/ABFieldConnect.js

I was still getting errors when an editor that was deconstruct()ed was trying to be updated.

[fix] prevent FieldConnect from trying to modify a destroyed widget.

---

AppBuilder/platform/views/viewComponent/ABViewCarouselComponent.js

This code causes a reload from the server each time there is a change to a datacollection...the result was that datacollection was reloaded from the server and sometimes the initial cursor would be reset.

stop reload form happening on datacollection events.

---

AppBuilder/platform/dataFields/ABFieldConnect.js
AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js

This is a big one, to sum up the code changes we are now identifying when a connected field has a M->1 or 1->1 connection type and we are loading the options from the server each time we request the options list.
The problem we are solving was the options were either doing one or two things depending on the type. They were either showing all options (even if one had been used on another record) or they were not showing the currently selected option thus breaking the UX because when editing a record you could not see the option you selected and upon saving you would erase that connection.
The solution was to identify the X->1 connection and not request local stored options and to always request them from the server. We also added back the filter that only showed options that were not …

fix issues with xxx->one options showing options that were already used

---

AppBuilder/platform/views/viewComponent/ABViewDetailCustomComponent.js
AppBuilder/platform/views/viewComponent/ABViewDetailItemComponent.js

fixes #274
Main change is splitting the detail item from a single `webix.template` to a `template` for both the label and value within a row or column based on label position.
```js
ui = {
cols: [labeTtemplate, valueTemplate]  // or rows:
}
```

fix detail multiline dsiplay

---

webpack/index.ejs

On the VPN sites, users often face the issue where they authenticate with CAS, and then end up in an infinite loop where the website keeps bouncing them back to CAS and back. The "Hello" page stares at them as the browser is stuck reloading forever.
The surface reason for this is that Sails is not sending the session cookie to the browser. With no cookie, the browser cannot prove its identity even after going through CAS. So Sails thinks it's a new unauthenticated user, and redirects to CAS again.
Something is blocking the session cookie. I spent days looking for it, but have not found it.
The `/favicon.ico` route does set a cookie. Some users can login after clearing the cache and restarting, or even switching to a different browser. (Favicon is not consistently loaded by the browser.) …

Fix website login problem

---

AppBuilder/platform/dataFields/ABFieldConnect.js

As Zach pointed out keep user data in local storage is a privacy concern. 
Since we are not actually using it, we don't need to store it.

Disable local storage of connect fields

---

webpack.common.js

- remove old gzip and license files when creating a new webpack build

cleanup old gzip and license files

---

AppBuilder/ABFactory.js
index.js
init/Bootstrap.js
js/webix/extras/tinymce.js
js/webix/locales/th-TH.js
js/webix/webixResources.js
package-lock.json
package.json
webpack.common.js

Including the webix sourcemaps, which makes debugging much easier.
Also noticed we load webix in multiple places to avoid problems when loading secondary webix files. So I moved all secondary files to a single spot and use dynamic imports to ensure we load webix first.
- include webix sourcemaps in webpack build
- load webix resources in set order to avoid missing dependencies

Improve webix load

---

AppBuilder/ABFactory.js
AppBuilder/platform/views/viewComponent/ABViewFormButtonComponent.js

Sentry is catching this error, seems to only happen on accounting.
[APPBUILDER-WEB-1A3](https://appdev-designs.sentry.io/issues/4631880265/)
- catch an uncaught form error and add context

catch uncaught error

---

AppBuilder/platform/ABModel.js

- [fix] have the delete handler actually call the "delete" event.
Not sure how we made it this long with not calling the "delete" event.  Maybe when we refactored things we made it so the "update" would also suffice, but we didn't leave any notes here, so I'm guessing it is a mistake.

[fix] have the delete handler actually call the "delete" event.

---

AppBuilder/platform/dataFields/ABFieldFile.js
AppBuilder/platform/dataFields/ABFieldImage.js
AppBuilder/platform/dataFields/ABFieldList.js
AppBuilder/platform/dataFields/ABFieldTree.js
AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js
AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
AppBuilder/platform/views/viewComponent/ABViewFormDatepickerComponent.js
resources/NetworkRest.js

- [fix] patches based upon Sentry issues
This addresses Sentry issues:
[APPBUILDER-WEB-1A9](https://appdev-designs.sentry.io/issues/4635015277/)
[APPBUILDER-WEB-1J4](https://appdev-designs.sentry.io/issues/4798536803/)
[APPBUILDER-WEB-1K3](https://appdev-designs.sentry.io/issues/4831605739/)
NOTE: that in the case of `ABViewDocxBuilderComponent.js` patch, I made sure that the error doesn't throw an exception, but it still remains to figure out what is the correct way to handle the situation.

[fix] patches based upon Sentry issues

---

AppBuilder/platform/dataFields/ABFieldConnect.js
AppBuilder/platform/dataFields/ABFieldUser.js
AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js

- [fix] ABViewFormConnect components that can select multiple values now handle encoded values "val1,val2" properly
I was debugging a problem with the display of the Site Administration -> Role -> Assign User form that wouldn't populate the existing data properly in the ABViewFormConnect field.  
Most of the current code related to checking and populating that form component only expected a single value "val1".  However connections that support multiple values will return them encoded as a string "val1,val2"  and our logic would fail to parse those correctly.

[fix] ABViewFormConnect components that can select multiple values now handle encoded values "val1,val2" properly

---

init/Bootstrap.js

[APPBUILDER-WEB-1PD](https://appdev-designs.sentry.io/issues/4927522791/)
- Fix slow network warning display while the site is loading ([APPBUILDER-WEB-1PD](https://appdev-designs.sentry.io/issues/4927522791/))

fix syntax for network warning during preload

---

webpack.common.js
webpack.dev.js
webpack.prod.js

The default html compression used in `html-webpack-plugin` will remove script type tags. In production tell the plugin not to remove these.
- Fix error loading `/config/preloader` because of incorrect MIME type

hotfix: err: refused to execute script ... MIME type 'text/html'

---

webpack.prod.js

Caused by pruning webix css that we use in the preload screen UI.
https://github.com/digi-serve/ns_app/issues/393
- fix: form display issue

hotfix: webix form css in production

---

AppBuilder/platform/ABModel.js
AppBuilder/platform/ABObject.js
AppBuilder/platform/dataFields/ABFieldConnect.js
AppBuilder/platform/dataFields/ABFieldUser.js
AppBuilder/platform/views/ABViewForm.js
AppBuilder/platform/views/viewComponent/ABViewCarouselComponent.js
AppBuilder/platform/views/viewComponent/ABViewChartComponent.js
AppBuilder/platform/views/viewComponent/ABViewConditionalContainerComponent.js
AppBuilder/platform/views/viewComponent/ABViewDetailComponent.js
AppBuilder/platform/views/viewComponent/ABViewFormComponent.js
AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
AppBuilder/platform/views/viewComponent/ABViewTextComponent.js
init/Bootstrap.js

We had certain dependencies on the client of depending on the Socket Updates to properly update our local client data.  
however, this won't display the application correctly when we set out Network = "rest".  So these changes should enable a local client app to properly update itself without the input of socket updates.
- [fix] have the client trigger local datacollection update handlers when we modify data.
- [fix] patch additional ABFieldUser quirks when working with values that need .id = .username
- [sync] with appropriate changes to core

Make Network Rest Great Again

---

AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js

I don't fully understand why be it appears that in some cases the await for `field.getAndPopulateOptions` doesn't resolve.
I'm seeing this locally and it causing issues with the test https://github.com/digi-serve/kitchensink_app/pull/101.
The form field still functions correctly. And just switching the order fixes the missing data-cy attributes. 
- fix setting data-cy attributes on form connect fields

Fix setting data-cy on a connected record form field

---

styles/ui.css

- Fix UI for clearing a value of a connected field.
Current UI:
After Fix:
No test needed because it is a small CSS change to help an element not be partial covered.

Fix the clear selection UI on connected fields.

---

AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js
styles/ui.css

- Right now there is no code to show the label of a connected field on top of the field in the form when there is an "Add New" button displayed. Therefore when forms are trying to display using label position "top" they do not look correct when displaying connected fields that have "add new" buttons.
Current UI:
New UI:
No test, this just just rearranging UI elements for specific scenarios.

Fix UI displaying connected fields with "Add New" buttons when label position is "top"

---

AppBuilder/platform/views/viewComponent/ABViewFormConnectComponent.js

- Fix label spacing on connected fields when "top" label position is used.
No test needed this is just a visual fix.
and when it happens multiple times it looks like this...
new code will help it look like this...

Fix spacing on connected fields labels.

---

index.js
init/Bootstrap.js

Don't wait for webix to load before starting bootstrap
- Adjustment to speed a site loading 
Covered in existing tests.

Adjust webix loading in parellel with init

---

AppBuilder/platform/views/viewComponent/ABViewFormCustomComponent.js

Found this while updating the staging2 site.
Not sure if there should be a better way to handle this, but at least this fix will prevent the site from crashing.
- [fix] site crashing when an ABViewFormComponent encounters a missing field
probably should have a test for this, but not an e2e test.  maybe a unit test?

Prevent site crash when encountering a missing field in ABViewFormComponent

---

AppBuilder/platform/dataFields/ABFieldUser.js
resources/NetworkRestSocket.js

A little bug I noticed while debugging.
- [fix] prevent undefined values from causing ABFieldUser.pullRelationValues() from crashing

Fix: prevent undefined values from causing ABFieldUser.pullRelationValues() from crashing

---

AppBuilder/platform/views/viewComponent/ABViewDetailComponent.js

This is the second part of an update that fixes a bug with the Details View.
https://github.com/digi-serve/ab_platform_web/issues/502
- Listen when DataCollection is empty to update Details View.

Listen to DataCollection to know if it is empty and update UI

---

AppBuilder/ABFactory.js
AppBuilder/platform/dataFields/ABFieldConnect.js
AppBuilder/platform/views/viewComponent/ABViewTabComponent.js

OK, James and Prin noticed an error on the Digiserve site where adding a connected row in a form would remove the connection on another record.
On the site, it was due to sending the whole `{Record}` back as the value, instead of just the `{uuid}` of the entry.  This patch ensures we are sending back the relevant `{uuid}` value.
- [fix] be sure to return just the proper uuid and not a full {Record} on ABFieldConnect values
- [fix] prevent bug when viewId is undefined
- [wip] adding an isNil() utilitiy for ABFactory
This new [Test](https://github.com/digi-serve/kitchensink_app/pull/107) is to validate this submission.  
NOTE: the combo test also validates partial correct operation.

Fix errors where Form submissions can reset other connections

---

AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js

- Fix bug where we should only load single record when cursor is set on a datacollection used in Docx.

hotfix look at cursor set for current data collection

---

AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js

- Previous implementation only returned the first 20 images of the original data collection's results. Thus excluding any user filters or filters based on linked or followed cursor. Now we loop through the data returned and get all images from it.

Loop through result data to find images to download.

---

AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js

- Fix issue where two data collections are in a repot and one has only a single object as a value and the other has an array of objects.

ensure that data we are looking at is an array

---

webix_custom_components/formioPreview.js

We previously assumed that passed in arrays would just be needing the .ids of the items.  However, we now have Form.io templates that are displaying embedded data from these records.
So we no longer simplify the array data to just .ids.

Fix Form.io data for passed in arrays

---

AppBuilder/ABFactory.js
AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js

- fix data types 
- Select List -> Connected Record
- Compare `string` and `integer` ids
- start to look at performance, takes ~2s to load
- slowest loading the assignments 
Related: https://github.com/digi-serve/plugin_ABDesigner/pull/274
-

Fixes to Team Chart

---

AppBuilder/platform/FilterComplex.js

Intended for issue [ns_app#543](https://github.com/digi-serve/ns_app/issues/543) 
My solution is to not only verify that a `.value` exists, but that it actually references a current query/datacollection.
Should probably also find additional condition types that fall into this category as well.
- [wip] add additional condition checks for datacollection and query conditions
- [fix] improper reference to this
- [wip] include in_query_field as well

add better condition checks for query and datacollection conditions

---

AppBuilder/rules/ruleActions/ABViewRuleActionObjectUpdater.js

This is a fix for [ns_app#542](https://github.com/digi-serve/ns_app/issues/542).
This also requires this [PR](https://github.com/digi-serve/appbuilder_class_core/pull/274) as part of the fix.
In our `v2` code, User fields are now Connected fields.  But the Record Rule Updater step didn't properly take that into consideration.
- [fix] prevent Record Rule Updater from treating User fields as ordinary Connected Fields

Prevent User Fields from being treated like Connected fields in Record Rule Updater

---

AppBuilder/platform/dataFields/ABFieldConnect.js
AppBuilder/platform/views/viewComponent/ABViewDataSelectComponent.js
AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js
styles/team-widget.css

https://github.com/digi-serve/planning/issues/581
I wanted to work on this more:
- Improve the skeleton chart (shown while loading data).
- Modify populate on data to the minimum we need.
- ~~Sometimes the chart doesn't load the first team (because the entity is not set yet).~~ https://github.com/digi-serve/ab_platform_web/pull/606
- ~~I'm not sure if the drag employee is creating assignments properly (might be a problem with my local objects)~~ https://github.com/digi-serve/ab_platform_web/pull/606
Most of the changes are just to move some functions to the class so we can reuse them.
- add a spinner while loading
- allow adding team assignments without refreshing the chart
- reduce requests made to load the content data

Teams performance improvements.

---

AppBuilder/platform/FilterComplex.js

- Add the 'By Query Field' filter option to connected fields with a 1:M relationship type

Add the 'By Query Field' filter option to connected fields with a 1:M relationship type

---

AppBuilder/platform/views/viewComponent/ABViewDetailComponent.js

This is another fix for [ns_app#550](https://github.com/digi-serve/ns_app/issues/550).
In this case, our `ab.datacollection.update`s were triggering a `cursorStale` with `null` as the parameter passed.
Our Detail Components were expecting proper values sent into the display data handler.
- [fix] make sure Detail components have data to work with on "cursorStale" with null passed in.

Make sure Detail components have data to work with on "cursorStale" handlers

---

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js

- hide the datapanel popup when switching to another page

fix: hide popup when swicthing to another page

---

AppBuilder/platform/views/viewComponent/ABViewOrgChartTeamsComponent.js

https://github.com/digi-serve/global-hr-update/issues/202
- fix: adding a person to a 2nd team removes first assignment

when drag from employee list don't end existing assignment

---

AppBuilder/ABFactory.js
AppBuilder/platform/views/viewComponent/ABViewDataSelectComponent.js
ui/portal_work.js

As we're moving closer to HR Teams release, I want to move away from needing to maintain different branches and building manually. I packaged the HR Teams Complex Widget as a plugin, in the style of ABDesigner. But this requires modification to ABDesigner, platform_web and core to load the relevant classes.
See the plugin code here: https://github.com/digi-serve/plugin_HRTeams
The main goal is code separation. I still think we need to work on a more accessible plugin system, that simplifies adding custom features to the platform.
- add support for plugins without pages
- add ABViewComponent class to ABFactory so a plugin can extend from it

Add support for view plugins

---

AppBuilder/ABFactory.js
AppBuilder/platform/ABModel.js
AppBuilder/platform/views/viewComponent/ABViewGridComponent.js
package.json
resources/NetworkRest.js
resources/NetworkRestSocket.js
webix_custom_components/formioBuilder.js

Initial Implementation of CSV Packing of our Data.
Currently we have been using json as our exchange format between our client and server.  For for larger data sets, the json format repeats a lot of data for the field names. ex:
```
[ 
{
"firstName": "Neo",
"lastName" : "Andersong",
},
{
"firstName": "Morpheous",
"lastName" : "",
},
{
"firstName": "Trinity",
"lastName" : ""
}
]
```
using csv, we can reduce the repeated column information:
```
firstName,lastName
"Neo","Anderson"
"Morpheous",""
"Trinity",""
```
The larger the dataset, the greater the savings. 
The previous data exchange format was
```
{
data: [{obj1}, {obj2}, ... {objN}],
total_bytes:xx,
}
```
This change now encodes our data in the following format:
```
{
csv_packed:{
data: "csv of primary data",
relations: { …
```

CSV Packing of Data (web platform)

---

AppBuilder/platform/ABDataCollection.js

This is to prevent duplicate loadData() requests when the responses take longer than the Datacollection's timeout/retry.
this depends on this [PR](https://github.com/digi-serve/appbuilder_class_core/pull/301).
- [fix] include current where condition as part of our loadData() blacklist key
- [wip] prevent repeated loadData() calls
I don't have any tests for this.

Add a blacklist to the loadData() routine to prevent duplicate loadData() requests

---

AppBuilder/platform/ABModel.js

If the incoming data was really large, our JSON.stringify() approach can result in a RAGE ERROR when running out of memory.
We fix this by only JSON.stringify() each individual row, and then sum the lengths together.
- [fix] Range Error when incoming data is too large: calculate unpacked length more efficiently

Fix RANGE ERROR when calculating the CSV Pack changes

---

ui/portal_work.js

Adds support for linking pages:
`http://admin.myappbuilder.com?app=[appID]&page=[pageID]`
- Allow linking to a page with query params
Tested locally

Add page routing by query params
